name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ../../runtime/Dockerfile --tag novatec/camunda-s3-connector:$(date +%s) --tag novatec/camunda-s3-connector:latest
