name: Release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY_BASE64 }}" | base64 --decode | gpg --batch --import
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Deploy connector-file-api
        run: |
          cd connector-file-api
          mvn build --settings ../.mvn/settings.xml
          
          mvn org.apache.maven.plugins:maven-install-plugin:3.1.2:install-file -Dfile=./target/connector-file-api-1.5.0-SNAPSHOT.jar -DgroupId=info.novatec.bpm.camunda.connector 
          -DartifactId=connector-file-api -Dversion=1.5.0-SNAPSHOT -Dpackaging=jar
          
          cd ../connector-aws-s3-libs
          mvn -X clean deploy --settings ../.mvn/settings.xml

        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Deploy connector-aws-s3-libs
        run: |
          cd connector-aws-s3-libs
          mvn -X clean deploy --settings ../.mvn/settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}